# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb23bbccf938fbe11bb5f1aa0261b0e93bf9fafdc3644602bef4f4fa9cdf357ae14fe0a5b9a610d80643391b3967518c06f1d120c40189dc8a0bc3a7d77cbf4

test:
  secret_key_base: 5f165a4058a5b8fba177d7d32d9bbb71f6a353ebc55e554e2790d37c85196ddcac966b1b774c7838c9d5707f45c564cbc301ab61457e6d136b340d09e4df659b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
