# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8822f165e9353b97cbe95de538e7aa45f7c6d19e9b180ac074cf932f8584ca28ba6b4d7b8553e4545a686b004d22ffc13be1ec33aa326fd2d2c30b8316c9d632

test:
  secret_key_base: 1698e2eac0b0fd4498e1947c423a81c5cf269ec710a99a9592ed51340595d7614a9c1459eb0cd7ba171f31aa7b965551a7d0321cd7c524dded4e3a2a6e457f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
