# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2abac75b741b70481ed9608e1caf620cd992b98dc0d79859170c95775f9ec9bf930182184aa8644022eadc2430a2551276ba7953b1c49c3aa10a3b153974c74e

test:
  secret_key_base: 7f37c0742f1c198e41d701194a05f7f0d7370fc3f903824f3461f3177ae7e568398ef06ea0423047e04414330004d692a1d081a86e698e65473b3b1bae0303ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
