source 'https://rubygems.org'

gem 'rails', '4.1.7'

# assets
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

# javascript
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'

# app server
gem 'unicorn'

group :development, :test do
  gem 'spring'
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
  gem 'guard-rspec'
  gem 'launchy'
end

group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group  :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'shoulda'
  gem 'vcr'
  gem 'webmock'
end

