# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27e4a79a4f5f8595593a12292a6379a8adf27ead9b48b6dbdc7f42b05848ae26d717b3b98c736e2bbe474e383642f7ac2f0d18d39243af8343ee1d4bc2fc587a

test:
  secret_key_base: cf9e7248e2b6536bc5373286292c6e156c3c856e33cc43fd0c3a422134c7e39aff6ce65fe7fa2984c0bcc5f418422a20bc49f6048a23dbfb32ce9135c63bd285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
