[package]
name = "fake-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.4", features=['derive', 'chrono', 'http', 'uuid']}
rand = "0.8"
