# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # 開発環境
  config.vm.define :dev do | dev |

    # Boxファイル
    dev.vm.box = "opscode-centos-6.6"

    # ホスト名
    config.vm.hostname = 'test'

    # Chef
    dev.vm.provision :chef_zero do |chef|
      chef.cookbooks_path = 'chef/cookbooks'
      chef.roles_path = 'chef/roles'
      chef.add_role 'dev'
    end
  end

end
