source 'https://rubygems.org'
ENV['NOKOGIRI_USE_SYSTEM_LIBRARIES'] = 'YES'

gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',                    group: :development
gem 'omniauth',         '~> 1.2.1'
gem 'omniauth-twitter', '~> 1.0.1'
gem 'kaminari', '~> 0.15.1'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem "ransack", '~> 1.2.2'
gem 'carrierwave', '~> 1.3.2'
gem 'nokogiri', '1.6.1'

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'minitest'
  gem 'factory_girl_rails'
end

group :test do
  gem 'capybara', '~> 2.4'
  gem "shoulda-matchers"
  gem 'poltergeist', '~> 1.5.0'
  gem 'database_cleaner', '~> 1.2.0'
end

